apiVersion: apps/v1
kind: Deployment
metadata:
  name: moonveil-site-backend-dev
  labels:
    k8s-app: moonveil-site-backend-dev
    qcloud-app: moonveil-site-backend-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: moonveil-site-backend-dev
      qcloud-app: moonveil-site-backend-dev
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: moonveil-site-backend-dev
        qcloud-app: moonveil-site-backend-dev
    spec:
      containers:
      - env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              key: MONGODB_URI
              name: mongo
              optional: false
        - name: MONGODB_URI_2048
          valueFrom:
            secretKeyRef:
              key: MONGODB_URI_2048
              name: mongo
              optional: false
        image: moonveil-entertainment.tencentcloudcr.com/moonveil/moonveil-site-backend
        imagePullPolicy: Always
        name: moonveil-site-backend-dev
        ports:
        - containerPort: 3000
          name: 3000-tcp
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: 250m
            memory: 256Mi
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: moonveil